FROM openjdk:8-jre-alpine

ENV APP_NAME=spring-security-saml-simple-service-provider-2.0.0.BUILD-SNAPSHOT.jar

COPY ./samples/boot/simple-service-provider/build/libs/${APP_NAME} /opt/

COPY ./secmgr1.crt /usr/local/share/ca-certificates/secmgr1.crt
RUN update-ca-certificates
RUN keytool -noprompt -import -alias secmgr1 -file /usr/local/share/ca-certificates/secmgr1.crt -keystore cacerts -storepass changeit

RUN apk update && apk add busybox && apk add curl

EXPOSE 8088

CMD ["sh", "-c", "java -jar /opt/${APP_NAME}"]


